# Copyright © JoDylan404 <john19911991@hotmail.fr>
# SPDX-License-Identifier:
# This file is maintained in https://github.com/JoDylan404/hogwarts-mystery-script-auto-clicker
github: [JoDylan404,]

# 4 custom sponsorship ####################################################
custom: [                                                                 #
                                                                          #
# parainage ###########################################                   #
                                                      #                   #
# Earn App                                            #                   #
"https://earnapp.com/i/83x6lce",                      #                   #
# remuneration sur les raport d'utilisation anonime   #                   #
                                                      #                   #
# SweatCoin                                           #                   #
# "https://sweatco.in/hi/jodylan",                    #                   #
# remuneration sur la marche et generation de crypto  #                   #
                                                      #                   #
# parainage ###########################################                   #
                                                                          #
# Cagnotte ############################################################## #
                                                                        # #
# Lydia                                                                 # #
"https://lydia-app.com/pots?id=hogwarts-mystery-script-auto-clicker",   # #
# fr 0% de tax 750 € de transactions/ mois                              # #
                                                                        # #
# Leetchi                                                               # #
"https://www.leetchi.com/c/script-auto-clicker-hogwarts-mystery",       # #
# fr 4 % - de 2000 € | 2,9 % de 2000€ à 200 000 € | 1,9 % + de 200 000 €# #
                                                                        # #
# Cagnotte ############################################################## #
                                                                          #
# Abonement et donation #############################################     #
                                                                    #     #
"https://www.paypal.com/donate/?hosted_button_id=2LXKW9JGBMFM6"     #     #
# Transactions par QRcode Supérieures ou égales à 10,01 EUR 0,60 %  #     #
# + commission fixe QR                                              #     #
# https://www.paypal.com/fr/webapps/mpp/merchant-fees               #     #
                                                                    #     #
# Abonement et don ##################################################     #
                                                                          #
]                                                                         #
# 4 custom sponsorship ####################################################

# Stripe
# demande le numero de telephone en public
# 1,4 % + 0,25 € pour les cartes Espace Economique Européen (+1,1% pour les cartes UK)
# 2,9 % + 0,25 € pour les cartes internationales

#########################################################################################################################

open_collective: hogwarts-mystery-script-auto-clicker # [https://opencollective.com/hogwarts-mystery-script-auto-clicker]
# en abonement mensuel 5$/mois | 100$/mois | donation (0% taxe)

patreon: user?u=87526817 # [patreon.com/user?u=87526817]
# fr abonement mensuel 3$/mois (taxe 5% des recettes mensuelles que vous percevez sur Patreon)

ko_fi: johndylan404 # [https://ko-fi.com/johndylan404] 
# en donation 5€ paypal ou stripe | plus d'option (taxe 5%)

tidelift: jodylan404 # [https://community.tidelift.com/jodylan404]
# en (gestion OpenSource)

community_bridge:
# en Contactez un expert CBI pour commencer. Processus de contrôle de la qualité basés sur le Web et consiergerie

liberapay: joDylan404
# Multi langue ~2 % pour les paiements traités par Stripe [4,9 % pour les paiements traités par PayPal non activer].

issuehunt: JoDylan404
# en plateforme de financement open source 3,6 % seront facturés en tant que frais de transaction[retrait uniquement PayPal].

otechie:
# Free-lance 29 $/mois essai de deux semaines web chat.

lfx_crowdfunding: 16390a1b-b191-462d-a66c-7c7c38ea63c8
# Ce projet est en attente d'approbation !
# This project is pending approval!
# en taxe ? |faire des dons à des projets open source https://openprofile.dev/profile/JoDylan404

# These are supported funding model platforms

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# otechie: # Replace with a single Otechie username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

# exemple :
# github: [octo, surt]
# patreon: octat
# tidelift: npm/o-package
# custom: ["https://www.paypal.me/t", t.com]
