# Copyright © JoDylan404 <john19911991@hotmail.fr>
# SPDX-License-Identifier:
# This file is maintained in https://github.com/JoDylan404/hogwarts-mystery-script-auto-clicker
github: [JoDylan404, josch]
custom: [https://earnapp.com/i/83x6lce] [https://sweatco.in/hi/jodylan]
patreon: [JohnDylan404] [patreon.com/user?u=87526817]
# These are supported funding model platforms

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
